/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSetupsRouteImport } from './routes/app.setups'
import { Route as AppPropfirmRouteImport } from './routes/app.propfirm'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppJournalRouteImport } from './routes/app.journal'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppSetupsIdRouteImport } from './routes/app.setups.$id'
import { Route as AppJournalNewRouteImport } from './routes/app.journal.new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupsRoute = AppSetupsRouteImport.update({
  id: '/setups',
  path: '/setups',
  getParentRoute: () => AppRoute,
} as any)
const AppPropfirmRoute = AppPropfirmRouteImport.update({
  id: '/propfirm',
  path: '/propfirm',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupsIdRoute = AppSetupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSetupsRoute,
} as any)
const AppJournalNewRoute = AppJournalNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppJournalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/journal': typeof AppJournalRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/propfirm': typeof AppPropfirmRoute
  '/app/setups': typeof AppSetupsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/journal/new': typeof AppJournalNewRoute
  '/app/setups/$id': typeof AppSetupsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/journal': typeof AppJournalRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/propfirm': typeof AppPropfirmRoute
  '/app/setups': typeof AppSetupsRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/journal/new': typeof AppJournalNewRoute
  '/app/setups/$id': typeof AppSetupsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/journal': typeof AppJournalRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/propfirm': typeof AppPropfirmRoute
  '/app/setups': typeof AppSetupsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/journal/new': typeof AppJournalNewRoute
  '/app/setups/$id': typeof AppSetupsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/journal'
    | '/app/profile'
    | '/app/propfirm'
    | '/app/setups'
    | '/app/'
    | '/app/journal/new'
    | '/app/setups/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/journal'
    | '/app/profile'
    | '/app/propfirm'
    | '/app/setups'
    | '/app'
    | '/app/journal/new'
    | '/app/setups/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/journal'
    | '/app/profile'
    | '/app/propfirm'
    | '/app/setups'
    | '/app/'
    | '/app/journal/new'
    | '/app/setups/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/setups': {
      id: '/app/setups'
      path: '/setups'
      fullPath: '/app/setups'
      preLoaderRoute: typeof AppSetupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propfirm': {
      id: '/app/propfirm'
      path: '/propfirm'
      fullPath: '/app/propfirm'
      preLoaderRoute: typeof AppPropfirmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journal': {
      id: '/app/journal'
      path: '/journal'
      fullPath: '/app/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/setups/$id': {
      id: '/app/setups/$id'
      path: '/$id'
      fullPath: '/app/setups/$id'
      preLoaderRoute: typeof AppSetupsIdRouteImport
      parentRoute: typeof AppSetupsRoute
    }
    '/app/journal/new': {
      id: '/app/journal/new'
      path: '/new'
      fullPath: '/app/journal/new'
      preLoaderRoute: typeof AppJournalNewRouteImport
      parentRoute: typeof AppJournalRoute
    }
  }
}

interface AppJournalRouteChildren {
  AppJournalNewRoute: typeof AppJournalNewRoute
}

const AppJournalRouteChildren: AppJournalRouteChildren = {
  AppJournalNewRoute: AppJournalNewRoute,
}

const AppJournalRouteWithChildren = AppJournalRoute._addFileChildren(
  AppJournalRouteChildren,
)

interface AppSetupsRouteChildren {
  AppSetupsIdRoute: typeof AppSetupsIdRoute
}

const AppSetupsRouteChildren: AppSetupsRouteChildren = {
  AppSetupsIdRoute: AppSetupsIdRoute,
}

const AppSetupsRouteWithChildren = AppSetupsRoute._addFileChildren(
  AppSetupsRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppJournalRoute: typeof AppJournalRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppPropfirmRoute: typeof AppPropfirmRoute
  AppSetupsRoute: typeof AppSetupsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppJournalRoute: AppJournalRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppPropfirmRoute: AppPropfirmRoute,
  AppSetupsRoute: AppSetupsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
